version: 3

extends: https://api.github.com/repos/example/pullapprove-config/contents/.pullapprove.yml

pullapprove_conditions:
- "'WIP' not in title"
- "base.ref == 'master'"

groups:
  code:
    reviewers:
      users:
      - barkasn
